# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/rsna1',
                'doc_host': 'https://yerx.github.io',
                'git_url': 'https://github.com/yerx/rsna1',
                'lib_path': 'rsna1'},
  'syms': {'rsna1.core': {'rsna1.core.foo': ('core.html#foo', 'rsna1/core.py')}}}
